FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
ARG CONFIGURATION=Production
WORKDIR /App

# Copy main csproj with dependencies and restore as distinct layers
COPY ./Producer/*.csproj .
COPY ./Infrastructure/*.csproj .
COPY ./Contracts/*.csproj .
# place project files to dirs with same name and restore packages
RUN for proj in *.csproj; do \
        filename=$(basename $proj) && \
        dirname=${filename%.*} && \
        mkdir $dirname && \
        mv $filename ./$dirname/; \
    done; \
    dotnet restore Producer/Producer.csproj --no-cache

# Copy a rest of files and publish
COPY ./Producer/* ./Producer
COPY ./Infrastructure/* ./Infrastructure
COPY ./Contracts/* ./Contracts

RUN dotnet publish Producer/Producer.csproj \
    --no-restore \
    --configuration $CONFIGURATION \
    --output /App/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "KafkaTest.Producer.dll"]